package com.ingramcontent.indiepub.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessProductFeed implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer feedTypeId;

	public ProcessProductFeed() {
	}

	public java.lang.Integer getFeedTypeId() {
		return this.feedTypeId;
	}

	public void setFeedTypeId(java.lang.Integer feedTypeId) {
		this.feedTypeId = feedTypeId;
	}

	public ProcessProductFeed(java.lang.Integer feedTypeId) {
		this.feedTypeId = feedTypeId;
	}

}